# Generated by Django 4.0 on 2022-06-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datatraining',
            old_name='path_file',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='datatraining',
            name='author',
        ),
        migrations.AddField(
            model_name='datatraining',
            name='judul',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='datatraining',
            name='penulis',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
