# Generated by Django 4.0 on 2022-06-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('tahun', models.IntegerField(null=True)),
                ('text_file', models.TextField()),
                ('path_file', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'data_training',
            },
        ),
    ]
