# Generated by Django 4.0 on 2022-06-28 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_rename_path_file_datatraining_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatraining',
            name='penulis',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
