# Generated by Django 4.0 on 2022-06-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plagiarisme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebyside',
            name='inisial',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
